spring:
  profiles:
    active: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.231.141.23:3306/threepay_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: admin
    #password: root
    password: admin_!@#123QWE
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  thymeleaf:
    cache: false
    prefix: classpath:/views/
    suffix: .html
    mode: html5
    encoding: utf-8
    servlet:
      content-type: text/html
  resources:
    #static-locations: classpath:/static/
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
#http config
httpConfig:
  connectionRequestTimeout: 10000
  connectTimeout: 10000
  socketTimeout: 10000
server:
  port: 9006
gateway:
  alipay:
    url: https://openapi.alipaydev.com/gateway.do
three:
  pay:
   notifyUrl: http://111.231.141.23:9005/AlipayNotify/pagePay
   forwardUrl: http://111.231.141.23:9006/channel/successForward