spring:
  profiles:
    active: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/threepay_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: admin
    #password: root
    password: admin_!@#123QWE
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  thymeleaf:
    cache: false
    prefix: classpath:/views/
    suffix: .html
    mode: html5
    encoding: utf-8
    servlet:
      content-type: text/html
  resources:
    #static-locations: classpath:/static/
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
#http config
httpConfig:
  connectionRequestTimeout: 30000
  connectTimeout: 30000
  socketTimeout: 30000
server:
  port: 9006
gateway:
  alipay:
    url: https://openapi.alipaydev.com/gateway.do
three:
  pay:
   notifyUrl: http://111.231.141.23:9005/AlipayNotify/pagePay
   forwardUrl: http://111.231.141.23:9006/channel/successForward