spring:
  profiles:
    active: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/threepay_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: admin
    #password: root
    password: admin_!@#123QWE
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  thymeleaf:
    cache: false
    prefix: classpath:/views/
    suffix: .html
    mode: html5
    encoding: utf-8
    servlet:
      content-type: text/html
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
server:
  port: 9001