language: java
sudo: false
script: mvn clean verify
after_success:
  - mvn clean test
  ## 生成测试报告
  - mvn jacoco:report
  ## 获取travis解密的token ,并调用coveralls-plugin上传报告
  - mvn coveralls:report -DrepoToken="${COVERALLS_TOKEN}"

## 加密后的token字串
env:
  global:
    - secure: "..............................."