spring:
  profiles:
    active: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/threepay_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: admin
    password: admin_!@#123QWE
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
#http config
httpConfig:
  connectionRequestTimeout: 3000
  connectTimeout: 3000
  socketTimeout: 5000
server:
  port: 9005
gateway:
  alipay:
    url: https://openapi.alipaydev.com/gateway.do
three:
  pay:
   notifyUrl: http://111.231.141.23:9005/AlipayNotify/pagePay
   forwardUrl: http://111.231.141.23:9006/channel/successForward