spring:
  profiles:
    active: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/threepay_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: admin
    password: admin_!@#123QWE
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
#http config
httpConfig:
  connectionRequestTimeout: 3000
  connectTimeout: 3000
  socketTimeout: 5000
server:
  port: 9002